# Generated by Django 5.2.17 on 2026-08-08 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_profit_brain_growth_utilization'),
        ('planning', '0003_dependencypreparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobasset',
            name='archive_inspected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobasset',
            name='declared_mime_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobasset',
            name='detected_mime_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobasset',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='planning.jobasset'),
        ),
        migrations.AddField(
            model_name='jobasset',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='jobasset',
            name='semantic_role',
            field=models.CharField(default='source', max_length=40),
        ),
        migrations.AddField(
            model_name='workplan',
            name='is_composite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workplan',
            name='max_steps',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='JobAssetManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('BLOCKED', 'Blocked')], default='BLOCKED', max_length=20)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('roles', models.JSONField(default=dict)),
                ('reason_codes', models.JSONField(default=list)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_manifest', to='control.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkPlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('operation', models.CharField(max_length=80)),
                ('worker_class', models.CharField(max_length=80)),
                ('input_spec', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('BLOCKED', 'Blocked'), ('READY', 'Ready'), ('EXECUTING', 'Executing'), ('NEEDS_REPAIR', 'Needs Repair'), ('QA_PASSED', 'Qa Passed'), ('FAILED', 'Failed')], default='BLOCKED', max_length=24)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('repair_attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_repair_attempts', models.PositiveSmallIntegerField(default=1)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('actual_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('repair_history', models.JSONField(default=list)),
                ('reason_codes', models.JSONField(default=list)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplan_steps', to='control.execution')),
                ('input_artifacts', models.ManyToManyField(blank=True, related_name='downstream_steps', to='control.artifact')),
                ('input_assets', models.ManyToManyField(blank=True, related_name='workplan_steps', to='planning.jobasset')),
                ('output_artifacts', models.ManyToManyField(blank=True, related_name='producing_steps', to='control.artifact')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='planning.workplan')),
                ('qa_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplan_steps', to='control.qaresult')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlanStepDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_links', to='planning.workplanstep')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_links', to='planning.workplanstep')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workplanstep',
            constraint=models.UniqueConstraint(fields=('plan', 'key'), name='uniq_workplan_step_key'),
        ),
        migrations.AddConstraint(
            model_name='workplanstep',
            constraint=models.UniqueConstraint(fields=('plan', 'sequence'), name='uniq_workplan_step_sequence'),
        ),
        migrations.AddConstraint(
            model_name='workplanstepdependency',
            constraint=models.UniqueConstraint(fields=('step', 'depends_on'), name='uniq_workplan_step_dependency'),
        ),
        migrations.AddConstraint(
            model_name='workplanstepdependency',
            constraint=models.CheckConstraint(condition=models.Q(('step', models.F('depends_on')), _negated=True), name='workplan_step_no_self_dependency'),
        ),
    ]
