import uuid
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("severity", models.CharField(default="INFO", max_length=16)),
                ("event_type", models.CharField(max_length=120)),
                ("actor", models.CharField(blank=True, max_length=120)),
                ("correlation_id", models.UUIDField(default=uuid.uuid4)),
                ("metadata", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="MarketCandidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("url", models.URLField()),
                ("status", models.CharField(default="MARKET_CANDIDATE", max_length=32)),
                ("api_or_mcp", models.BooleanField(default=False)),
                ("payout_method", models.CharField(blank=True, max_length=120)),
                ("south_africa_support", models.BooleanField(default=False)),
                ("automation_allowed", models.BooleanField(default=False)),
                ("webdock_compatible", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("status", models.CharField(choices=[("LIVE", "Live"), ("WATCH_ONLY", "Watch Only"), ("PAYOUT_BLOCKED", "Payout Blocked"), ("AUTH_EXPIRED", "Auth Expired"), ("DEGRADED", "Degraded"), ("NO_SUPPLY", "No Supply"), ("POLICY_DISABLED", "Policy Disabled"), ("UNPROFITABLE", "Unprofitable")], default="WATCH_ONLY", max_length=32)),
                ("enabled", models.BooleanField(default=False)),
                ("payout_ready", models.BooleanField(default=False)),
                ("south_africa_verified", models.BooleanField(default=False)),
                ("fee_rate", models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ("payment_model", models.CharField(blank=True, max_length=100)),
                ("policy_hash", models.CharField(blank=True, max_length=128)),
                ("last_policy_check", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OwnerSecurityProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("totp_secret_encrypted", models.TextField(blank=True)),
                ("totp_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("security_version", models.PositiveIntegerField(default=1)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="LoginChallenge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code_hash", models.CharField(max_length=255)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="RefreshSession",
            fields=[
                ("jti", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("family_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("replaced_by_jti", models.UUIDField(blank=True, null=True)),
                ("user_agent_hash", models.CharField(blank=True, max_length=64)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("task_class", models.CharField(max_length=100)),
                ("reward", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("state", models.CharField(choices=[("DISCOVERED", "Discovered"), ("EXPECTED", "Expected"), ("CLAIMED", "Claimed"), ("AWARDED", "Awarded"), ("EXECUTING", "Executing"), ("SUBMITTED", "Submitted"), ("ACCEPTED", "Accepted"), ("PAYOUT_PENDING", "Payout Pending"), ("SETTLED", "Settled"), ("FAILED", "Failed")], default="DISCOVERED", max_length=32)),
                ("normalized_payload", models.JSONField(default=dict)),
                ("marketplace", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="control.marketplace")),
            ],
        ),
        migrations.CreateModel(
            name="JobLock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("node_id", models.CharField(max_length=120)),
                ("lease_until", models.DateTimeField()),
                ("fencing_token", models.PositiveBigIntegerField(default=1)),
                ("job", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="control.job")),
            ],
        ),
        migrations.CreateModel(
            name="JobScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("p_acquire", models.DecimalField(decimal_places=5, max_digits=6)),
                ("p_accept", models.DecimalField(decimal_places=5, max_digits=6)),
                ("p_payment", models.DecimalField(decimal_places=5, max_digits=6)),
                ("expected_genx_cost", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("expected_external_cost", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("expected_cash", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("expected_profit", models.DecimalField(decimal_places=2, max_digits=14)),
                ("expected_profit_per_minute", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("expected_profit_per_genx_credit", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("expected_minutes", models.PositiveIntegerField()),
                ("decision", models.CharField(default="WATCH", max_length=32)),
                ("reason_codes", models.JSONField(default=list)),
                ("score_version", models.CharField(default="v1", max_length=32)),
                ("job", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="control.job")),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.CharField(max_length=120, primary_key=True, serialize=False)),
                ("worker_class", models.CharField(max_length=80)),
                ("version", models.CharField(default="0.1.0", max_length=40)),
                ("node", models.CharField(default="VPS1", max_length=120)),
                ("status", models.CharField(default="OFFLINE", max_length=32)),
                ("last_heartbeat", models.DateTimeField(default=django.utils.timezone.now)),
                ("current_job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="control.job")),
            ],
        ),
        migrations.CreateModel(
            name="GenXCall",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model", models.CharField(max_length=120)),
                ("external_job_id", models.CharField(blank=True, max_length=255)),
                ("credits", models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ("usage", models.JSONField(default=dict)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(max_length=32)),
                ("cost_equivalent", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="control.job")),
                ("worker", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="control.worker")),
            ],
        ),
        migrations.CreateModel(
            name="QAResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("check_type", models.CharField(max_length=100)),
                ("passed", models.BooleanField()),
                ("score", models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ("evidence", models.JSONField(default=dict)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="control.job")),
            ],
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                ("status", models.CharField(default="REQUIRED", max_length=32)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="control.job")),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remote_id", models.CharField(blank=True, max_length=255)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(default="PENDING", max_length=32)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="control.job")),
            ],
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gross", models.DecimalField(decimal_places=2, max_digits=14)),
                ("fee", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("net", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("state", models.CharField(choices=[("EARNED", "Earned"), ("PAYOUT_PENDING", "Payout Pending"), ("SETTLED", "Settled"), ("REVERSED", "Reversed")], max_length=32)),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="control.job")),
            ],
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(db_index=True, max_length=160)),
                ("account", models.CharField(max_length=120)),
                ("counter_account", models.CharField(max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("event_type", models.CharField(max_length=80)),
                ("metadata", models.JSONField(default=dict)),
            ],
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(fields=("marketplace", "external_id"), name="uniq_market_external_job"),
        ),
    ]
