import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("control", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="external_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="payout",
            name="earned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="pending_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="entry_key",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="jobscore",
            name="max_genx_credits",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="genxcall",
            name="request_key",
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="genxcall",
            name="task_class",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="genxcall",
            name="marketplace_slug",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="genxcall",
            name="estimated_credits",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="genxcall",
            name="max_allowed_credits",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="genxcall",
            name="requested_metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="genxcall",
            name="result_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="genxcall",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genxcall",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genxcall",
            name="error_code",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="MarketplaceCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("credential_type", models.CharField(max_length=80)),
                ("encrypted_value", models.TextField()),
                ("key_id", models.CharField(blank=True, max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("marketplace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="credentials", to="control.marketplace")),
            ],
        ),
        migrations.CreateModel(
            name="MarketPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policy_hash", models.CharField(max_length=128)),
                ("source_url", models.URLField(blank=True)),
                ("automation_allowed", models.BooleanField(default=False)),
                ("webdock_compatible", models.BooleanField(default=False)),
                ("checked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("snapshot", models.JSONField(default=dict)),
                ("marketplace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="policy_versions", to="control.marketplace")),
            ],
        ),
        migrations.CreateModel(
            name="MarketHealth",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("api_ok", models.BooleanField(default=False)),
                ("auth_ok", models.BooleanField(default=False)),
                ("payout_ok", models.BooleanField(default=False)),
                ("supply_ok", models.BooleanField(default=False)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=120)),
                ("checked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("details", models.JSONField(default=dict)),
                ("marketplace", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="health_snapshot", to="control.marketplace")),
            ],
        ),
        migrations.CreateModel(
            name="PayoutAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rail", models.CharField(max_length=80)),
                ("external_reference", models.CharField(blank=True, max_length=255)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("status", models.CharField(default="PENDING", max_length=32)),
                ("south_africa_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("details", models.JSONField(default=dict)),
                ("marketplace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payout_accounts", to="control.marketplace")),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(default="APPLY", max_length=32)),
                ("offered_price", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("message", models.TextField(blank=True)),
                ("remote_reference", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="PENDING", max_length=32)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="applications", to="control.job")),
            ],
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("remote_reference", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="PENDING", max_length=32)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bids", to="control.job")),
            ],
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remote_reference", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="CLAIMED", max_length=32)),
                ("claimed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="claims", to="control.job")),
            ],
        ),
        migrations.CreateModel(
            name="JobMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remote_id", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(max_length=80)),
                ("direction", models.CharField(choices=[("IN", "Inbound"), ("OUT", "Outbound")], max_length=16)),
                ("content_hash", models.CharField(max_length=64)),
                ("content", models.TextField(blank=True)),
                ("action_required", models.BooleanField(default=False)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="control.job")),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.CharField(max_length=120, primary_key=True, serialize=False)),
                ("hostname", models.CharField(max_length=255)),
                ("release_version", models.CharField(blank=True, max_length=80)),
                ("role_profile", models.CharField(default="controller-worker", max_length=80)),
                ("health", models.CharField(default="UNKNOWN", max_length=32)),
                ("cpu_percent", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("ram_percent", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("disk_percent", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("last_heartbeat", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="WorkerVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("worker_class", models.CharField(max_length=80)),
                ("version", models.CharField(max_length=40)),
                ("git_sha", models.CharField(blank=True, max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Execution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("node_id", models.CharField(default="VPS1", max_length=120)),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(default="QUEUED", max_length=32)),
                ("workspace", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, max_length=120)),
                ("error_detail", models.TextField(blank=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="executions", to="control.job")),
                ("worker", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="control.worker")),
            ],
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(default="deliverable", max_length=80)),
                ("path", models.CharField(blank=True, max_length=700)),
                ("url", models.URLField(blank=True)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("accepted", models.BooleanField(default=False)),
                ("retention_class", models.CharField(default="JOB_EVIDENCE", max_length=32)),
                ("execution", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="artifacts", to="control.execution")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="control.job")),
            ],
        ),
        migrations.CreateModel(
            name="GenXModelCatalog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_id", models.CharField(max_length=160, primary_key=True, serialize=False)),
                ("category", models.CharField(blank=True, db_index=True, max_length=40)),
                ("provider", models.CharField(blank=True, max_length=120)),
                ("active", models.BooleanField(default=True)),
                ("price_hint", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("model_payload", models.JSONField(default=dict)),
                ("pricing_payload", models.JSONField(default=dict)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="GenXAccountSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("available_credits", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("raw", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ModelStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model", models.CharField(max_length=160)),
                ("task_class", models.CharField(max_length=100)),
                ("attempts", models.PositiveBigIntegerField(default=0)),
                ("accepted", models.PositiveBigIntegerField(default=0)),
                ("revenue", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("credits", models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ("cost_equivalent", models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ("profit", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("total_latency_ms", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TreasuryBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.CharField(max_length=120)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("earned", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("pending", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("settled", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("marketplace", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="control.marketplace")),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("severity", models.CharField(default="INFO", max_length=16)),
                ("alert_type", models.CharField(max_length=120)),
                ("status", models.CharField(default="OPEN", max_length=32)),
                ("message", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=160, unique=True)),
                ("value", models.JSONField(default=dict)),
                ("sensitive", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="qaresult",
            name="execution",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="control.execution"),
        ),
        migrations.AddField(
            model_name="submission",
            name="artifact",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="control.artifact"),
        ),
        migrations.AddField(
            model_name="submission",
            name="response",
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name="payout",
            constraint=models.UniqueConstraint(fields=("job", "currency"), name="uniq_job_payout_currency"),
        ),
        migrations.AddConstraint(
            model_name="marketplacecredential",
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=("marketplace", "credential_type"), name="uniq_active_market_credential_type"),
        ),
        migrations.AddConstraint(
            model_name="marketpolicyversion",
            constraint=models.UniqueConstraint(fields=("marketplace", "policy_hash"), name="uniq_market_policy_hash"),
        ),
        migrations.AddConstraint(
            model_name="jobmessage",
            constraint=models.UniqueConstraint(condition=~models.Q(remote_id=""), fields=("job", "remote_id"), name="uniq_job_remote_message"),
        ),
        migrations.AddConstraint(
            model_name="workerversion",
            constraint=models.UniqueConstraint(fields=("worker_class", "version"), name="uniq_worker_class_version"),
        ),
        migrations.AddConstraint(
            model_name="execution",
            constraint=models.UniqueConstraint(fields=("job", "attempt"), name="uniq_job_execution_attempt"),
        ),
        migrations.AddConstraint(
            model_name="modelstat",
            constraint=models.UniqueConstraint(fields=("model", "task_class"), name="uniq_model_task_stat"),
        ),
        migrations.AddConstraint(
            model_name="treasurybalance",
            constraint=models.UniqueConstraint(fields=("account", "currency"), name="uniq_treasury_account_currency"),
        ),
    ]
