# Generated by Django 5.2.17 on 2026-08-08 19:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_profit_brain_growth_utilization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIntegrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adapter_name', models.CharField(max_length=160)),
                ('adapter_version', models.CharField(default='v1', max_length=40)),
                ('source_wired', models.BooleanField(default=False)),
                ('autonomous_acquisition_enabled', models.BooleanField(default=False)),
                ('policy_verified', models.BooleanField(default=False)),
                ('docs_checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('auth_method', models.CharField(blank=True, max_length=160)),
                ('rate_limit', models.CharField(blank=True, max_length=160)),
                ('payout_method', models.CharField(blank=True, max_length=160)),
                ('capabilities', models.JSONField(default=dict)),
                ('source_urls', models.JSONField(default=list)),
                ('blockers', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=dict)),
                ('marketplace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_profile', to='control.marketplace')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('autonomous_acquisition_enabled', False), ('policy_verified', True), _connector='OR'), name='market_acquisition_requires_verified_policy')],
            },
        ),
    ]
