# Generated by Django 5.2.17 on 2026-08-09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


_NO_SELLER_CAPABILITIES = {
    "publish_service": False,
    "update_service": False,
    "pause_service": False,
    "receive_orders": False,
    "order_status": False,
    "service_messages": False,
    "service_delivery": False,
    "usage_metering": False,
    "seller_payment": False,
    "seller_webhooks": False,
    "subscription_sales": False,
    "pay_per_call": False,
    "project_sales": False,
}

_LEGACY_PROFILE_ENRICHMENTS = {
    "agentgigs": {
        "revenue_channels": ["POSTED_JOB"], "job_acquisition_mode": "REST_API",
        "seller_mode": "NONE_VERIFIED", "settlement_rail": "STRIPE_CONNECT_ACCOUNT_PROOF_REQUIRED",
        "hosting_policy": "WEBDOCK_SAFE", "api_contract_state": "OFFICIAL_REST_CONTRACT",
    },
    "dealwork": {
        "revenue_channels": ["POSTED_JOB"], "job_acquisition_mode": "MCP_JOB_TOOLS",
        "seller_mode": "SERVICE_LISTING_CONTRACT_UNVERIFIED", "settlement_rail": "WALLET_WITHDRAWAL_RAIL_UNVERIFIED",
        "hosting_policy": "WEBDOCK_SAFE", "api_contract_state": "OFFICIAL_MCP_JOB_CONTRACT",
    },
    "callboard": {
        "revenue_channels": ["POSTED_JOB"], "job_acquisition_mode": "OPENAPI_V2",
        "seller_mode": "NONE_VERIFIED", "settlement_rail": "STRIPE_CONNECT_ACCOUNT_PROOF_REQUIRED",
        "hosting_policy": "WEBDOCK_SAFE", "api_contract_state": "OFFICIAL_OPENAPI_CONTRACT",
    },
    "taskbounty": {
        "revenue_channels": ["BOUNTY"], "job_acquisition_mode": "REST_API",
        "seller_mode": "NONE_VERIFIED", "settlement_rail": "USD_BANK_TRANSFER_ONLY",
        "hosting_policy": "WEBDOCK_SAFE", "api_contract_state": "OFFICIAL_REST_CONTRACT",
    },
    "opire": {
        "revenue_channels": ["BOUNTY"], "job_acquisition_mode": "SOURCE_WIRED_IMPORT_MANUAL_WORKFLOW",
        "seller_mode": "NO_SOLVER_MUTATION_CONTRACT", "settlement_rail": "STRIPE_REWARD_CREATOR_PAYMENT_UNVERIFIED",
        "hosting_policy": "WEBDOCK_SAFE", "api_contract_state": "SOURCE_IMPORT_ONLY_NO_SOLVER_MUTATION",
    },
    "algora": {
        "revenue_channels": ["BOUNTY"], "job_acquisition_mode": "SOURCE_WIRED_IMPORT",
        "seller_mode": "SOLVER_MUTATION_CONTRACT_UNVERIFIED", "settlement_rail": "PAYOUT_ONBOARDING_RAIL_UNVERIFIED",
        "hosting_policy": "WEBDOCK_SAFE", "api_contract_state": "SOURCE_IMPORT_ONLY_SOLVER_MUTATION_UNVERIFIED",
    },
}


def _enrich_legacy_market_profiles(apps, schema_editor):
    MarketIntegrationProfile = apps.get_model("control", "MarketIntegrationProfile")
    for slug, values in _LEGACY_PROFILE_ENRICHMENTS.items():
        MarketIntegrationProfile.objects.filter(marketplace__slug=slug).update(
            seller_capabilities=dict(_NO_SELLER_CAPABILITIES),
            currency="USD",
            manual_onboarding_required=True,
            **values,
        )


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [("control", "0009_safetyfinding_bountyprogram_programscopeversion_and_more")]

    operations = [
        migrations.AddField(model_name="marketintegrationprofile", name="api_contract_state", field=models.CharField(default="UNVERIFIED", max_length=80)),
        migrations.AddField(model_name="marketintegrationprofile", name="automation_status", field=models.CharField(default="BLOCKED", max_length=80)),
        migrations.AddField(model_name="marketintegrationprofile", name="currency", field=models.CharField(default="USD", max_length=3)),
        migrations.AddField(model_name="marketintegrationprofile", name="hosting_policy", field=models.CharField(default="UNVERIFIED", max_length=40)),
        migrations.AddField(model_name="marketintegrationprofile", name="job_acquisition_mode", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="marketintegrationprofile", name="manual_onboarding_required", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="marketintegrationprofile", name="payout_proof_state", field=models.CharField(default="UNVERIFIED", max_length=80)),
        migrations.AddField(model_name="marketintegrationprofile", name="revenue_channels", field=models.JSONField(default=list)),
        migrations.AddField(model_name="marketintegrationprofile", name="seller_capabilities", field=models.JSONField(default=dict)),
        migrations.AddField(model_name="marketintegrationprofile", name="seller_mode", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="marketintegrationprofile", name="settlement_rail", field=models.CharField(blank=True, max_length=120)),
        migrations.RunPython(_enrich_legacy_market_profiles, _noop_reverse),
        migrations.CreateModel(
            name="MarketServiceListing",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("remote_listing_id", models.CharField(blank=True, max_length=255)), ("remote_reference", models.CharField(blank=True, max_length=700)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("READY", "Ready"), ("PUBLISHED", "Published"), ("PAUSED", "Paused"), ("BLOCKED", "Blocked"), ("STALE", "Stale"), ("FAILED", "Failed")], default="DRAFT", max_length=20)),
                ("published_price", models.DecimalField(decimal_places=2, default=0, max_digits=14)), ("currency", models.CharField(default="USD", max_length=3)),
                ("pricing_model", models.CharField(choices=[("FIXED_PROJECT", "Fixed Project"), ("PER_CALL", "Per Call"), ("PER_UNIT", "Per Unit"), ("SUBSCRIPTION", "Subscription"), ("OUTCOME", "Outcome")], max_length=24)),
                ("published_at", models.DateTimeField(blank=True, null=True)), ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("platform_metadata", models.JSONField(default=dict)), ("remote_version", models.CharField(blank=True, max_length=80)),
                ("policy_hash", models.CharField(blank=True, max_length=128)), ("failure_code", models.CharField(blank=True, max_length=120)),
                ("failure_detail", models.TextField(blank=True)),
                ("marketplace", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="service_listings", to="control.marketplace")),
            ],
        ),
        migrations.CreateModel(
            name="InboundOrder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("remote_order_id", models.CharField(max_length=255)), ("idempotency_key", models.CharField(max_length=255)),
                ("buyer_reference", models.CharField(blank=True, max_length=255)), ("requirements", models.JSONField(default=dict)),
                ("input_assets", models.JSONField(default=list)), ("quoted_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=3)), ("platform_fee", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("funding_state", models.CharField(default="UNVERIFIED", max_length=80)), ("deadline", models.DateTimeField(blank=True, null=True)),
                ("remote_state", models.CharField(blank=True, max_length=80)), ("messages", models.JSONField(default=list)),
                ("usage", models.JSONField(default=dict)),
                ("settlement_reference", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("RECEIVED", "Received"), ("PREFLIGHT_BLOCKED", "Preflight Blocked"), ("READY", "Ready"), ("ACCEPTED", "Accepted"), ("DELIVERED", "Delivered"), ("PAYOUT_PENDING", "Payout Pending"), ("SETTLED", "Settled"), ("REVERSED", "Reversed"), ("FAILED", "Failed")], default="RECEIVED", max_length=24)),
                ("economic_preflight", models.JSONField(default=dict)), ("request_digest", models.CharField(max_length=64)), ("authenticated_at", models.DateTimeField()),
                ("job", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="inbound_order", to="control.job")),
                ("marketplace", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inbound_orders", to="control.marketplace")),
                ("listing", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="inbound_orders", to="control.marketservicelisting")),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioDecision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_type", models.CharField(max_length=40)), ("revenue_channel", models.CharField(max_length=40)),
                ("rank", models.PositiveIntegerField()), ("score", models.DecimalField(decimal_places=6, max_digits=18)),
                ("selected", models.BooleanField(default=False)), ("expected_net_profit", models.DecimalField(decimal_places=2, max_digits=14)),
                ("risk_adjusted_profit", models.DecimalField(decimal_places=2, max_digits=14)), ("profit_per_minute", models.DecimalField(decimal_places=4, max_digits=14)),
                ("payout_probability", models.DecimalField(decimal_places=6, max_digits=7)), ("acceptance_probability", models.DecimalField(decimal_places=6, max_digits=7)),
                ("inputs", models.JSONField(default=dict)),
                ("inbound_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="portfolio_decisions", to="control.inboundorder")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="portfolio_decisions", to="control.job")),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOffering",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("slug", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=160)), ("description", models.TextField(blank=True)),
                ("capability", models.CharField(max_length=100)), ("operation", models.CharField(max_length=100)), ("worker_class", models.CharField(max_length=100)),
                ("pricing_model", models.CharField(choices=[("FIXED_PROJECT", "Fixed Project"), ("PER_CALL", "Per Call"), ("PER_UNIT", "Per Unit"), ("SUBSCRIPTION", "Subscription"), ("OUTCOME", "Outcome")], max_length=24)),
                ("currency", models.CharField(default="USD", max_length=3)), ("advertised_price", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("minimum_profitable_price", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("platform_fee_rate", models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ("expected_genx_cost", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("max_genx_credits", models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ("expected_external_cost", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("expected_operational_cost", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("expected_minutes", models.PositiveIntegerField(default=1)), ("sla_minutes", models.PositiveIntegerField(default=1440)),
                ("input_schema", models.JSONField(default=dict)), ("output_schema", models.JSONField(default=dict)),
                ("terms_metadata", models.JSONField(default=dict)), ("proof_evidence", models.JSONField(default=dict)),
                ("enabled", models.BooleanField(default=False)), ("accepting_orders", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("proof_state", models.CharField(choices=[("UNPROVEN", "Unproven"), ("SOURCE_PROVEN", "Source Proven"), ("EXECUTION_PROVEN", "Execution Proven"), ("SELLABLE", "Sellable")], default="UNPROVEN", max_length=24)),
            ],
            options={"constraints": [
                models.CheckConstraint(condition=models.Q(("advertised_price__gte", 0)), name="service_advertised_price_nonnegative"),
                models.CheckConstraint(condition=models.Q(("minimum_profitable_price__gte", 0)), name="service_minimum_price_nonnegative"),
                models.CheckConstraint(condition=models.Q(("platform_fee_rate__gte", 0), ("platform_fee_rate__lt", 1)), name="service_fee_rate_valid"),
                models.CheckConstraint(condition=models.Q(("expected_genx_cost__gte", 0)), name="service_genx_cost_nonnegative"),
                models.CheckConstraint(condition=models.Q(("max_genx_credits__gte", 0)), name="service_genx_credits_nonnegative"),
                models.CheckConstraint(condition=models.Q(("expected_external_cost__gte", 0)), name="service_external_cost_nonnegative"),
                models.CheckConstraint(condition=models.Q(("expected_operational_cost__gte", 0)), name="service_operational_cost_nonnegative"),
            ]},
        ),
        migrations.AddField(model_name="marketservicelisting", name="offering", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="market_listings", to="control.serviceoffering")),
        migrations.CreateModel(
            name="InboundSettlementEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
                ("remote_event_id", models.CharField(max_length=255)),
                ("state", models.CharField(choices=[("AUTHORIZED", "Authorized"), ("ESCROW", "Escrow"), ("PAYOUT_PENDING", "Payout Pending"), ("SETTLED", "Settled"), ("REVERSED", "Reversed")], max_length=24)),
                ("gross", models.DecimalField(decimal_places=2, max_digits=14)), ("fee", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("net", models.DecimalField(decimal_places=2, max_digits=14)), ("currency", models.CharField(default="USD", max_length=3)),
                ("authoritative", models.BooleanField(default=False)), ("evidence_source", models.CharField(max_length=120)),
                ("evidence", models.JSONField(default=dict)), ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="settlement_events", to="control.inboundorder")),
            ],
            options={"constraints": [
                models.UniqueConstraint(fields=("order", "remote_event_id"), name="uniq_inbound_settlement_event"),
                models.CheckConstraint(condition=models.Q(("gross__gte", 0)), name="inbound_settlement_gross_nonnegative"),
                models.CheckConstraint(condition=models.Q(("fee__gte", 0), ("fee__lte", models.F("gross"))), name="inbound_settlement_fee_valid"),
                models.CheckConstraint(condition=models.Q(("net__gte", 0)), name="inbound_settlement_net_nonnegative"),
            ]},
        ),
        migrations.AddConstraint(model_name="inboundorder", constraint=models.UniqueConstraint(fields=("marketplace", "remote_order_id"), name="uniq_market_inbound_order")),
        migrations.AddConstraint(model_name="inboundorder", constraint=models.UniqueConstraint(fields=("marketplace", "idempotency_key"), name="uniq_market_inbound_idempotency")),
        migrations.AddConstraint(model_name="inboundorder", constraint=models.CheckConstraint(condition=models.Q(("quoted_price__gt", 0)), name="inbound_order_price_positive")),
        migrations.AddConstraint(model_name="inboundorder", constraint=models.CheckConstraint(condition=models.Q(("platform_fee__gte", 0), ("platform_fee__lte", models.F("quoted_price"))), name="inbound_order_fee_valid")),
        migrations.AddConstraint(model_name="marketservicelisting", constraint=models.UniqueConstraint(fields=("offering", "marketplace"), name="uniq_service_market_listing")),
        migrations.AddConstraint(model_name="marketservicelisting", constraint=models.CheckConstraint(condition=models.Q(("published_price__gte", 0)), name="service_listing_price_nonnegative")),
    ]
