# Generated by Django 5.2.17 on 2026-08-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_marketintegrationprofile_api_connection_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcandidate',
            name='break_even_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcandidate',
            name='commercial_evidence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='productcandidate',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='productcandidate',
            name='first_sale_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcandidate',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcandidate',
            name='return_on_production_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
